#import "lib.typ"
#import "@preview/finite:0.5.0": automaton

#let title = [Languages and Machines]
#set page(
   paper: "a4",
   header: align(left, title),
   numbering: "1",
)

#align(center, text(17pt)[
   *#title*
   
   Matteo Bongiovanni\
   Roman Gazarek
])

= Regular Languages
== Operations
- $L = {a a, b b}$ and $M = {c, d}$ then $L M = {a a c, a a  d, b b c, b b d}$
- ${a,b, a b}^2 = {a a, a b, a a b, b a, b b, b a b, a b a, a b b, a b a b}$
- ${a,b}^* = {epsilon} union {a, b} union {a a, b b, b a, b b} union {a a a...}$
- ${a b, c d}^R = {b a, d c}$ 

== Definitions
Recursively defined over an alphabet $Sigma$ from
  - $emptyset$
  - ${epsilon}$
  - ${a}$ for all $a in Sigma$
by applying union, concatenation, and Kleene star.

*Regular Expressions*: A notation to denote regular languages
- Example: $a^*(c|d)b^*$ denotes the *regular set* ${a}^*({c}union{d}){b}^*$
- The regular expression of a set is not unique

== Regular Expressions
Regular Expression Identities : \
- $emptyset u = u emptyset = emptyset$
- $epsilon u = u epsilon = u$
- $emptyset^* = emptyset$
- $epsilon^* = epsilon$
- $u | v = v | u$
- $u | emptyset = u$
- $u | u = u$
- $u(v | w) = u v | u w$
- $(u | v)w = u w | v w$
- $u^* = (u^*)^*$
- $(u | v)^* = (u^* | v)^* = u^*(u | v)^* = (u | v u^*)^* = (u^* v^*) = u^*(v u^*)^* = (u^* v u^*)^*$


== DFSM, NFSM, N$epsilon$FSM

A *deterministic finite state machine (DFSM)* is a quintuple $M = (Q, Sigma, delta, q_0, F)$ where:
- $Q$ is a finite set of states
- $Sigma$ is the input alphabet
- $delta : Q times Sigma arrow Q$ is the _transition function_
- $q_0$ is the initial state
- $F subset.eq$ is a set of _accepting_ (or _final_) states\
When symbol $a$ is read in a state $q_n$, the state becomes $delta (q_n, a)$.
#align(center, automaton(
  (
  q0: (q1: "a"),
  q1: (),
  ),
  labels: (q0: $q_n$, q1: $q_i$)
  ))
#align(center, text(12pt)[
  $delta(q_n, a) = q_i$
])



== FSM to regular expression
== FSM minimization
== Pumping lemma for regular languages
== Regular expression identities
== Regular grammars
A grammar $(V, Sigma, P, S)$ is *regular* if every production rule in $P$ has one of the following forms $(a in Sigma$ and $A, B in V)$:
- $A arrow a B$ or
- $A arrow epsilon$
A language is regular *iff* it is generated by a regular grammar.\
*Example*: A non-regular grammar for the regular expression $(a b)^* a^*$:\
#align(center, text(12pt)[$S arrow a b S A | epsilon \ A arrow A a | epsilon $])\
An equivalent regular grammar:\
#align(center, text(12pt)[$S arrow a B | epsilon \ B arrow b S | b A \ A arrow a A | epsilon$])

=== Useful, Generating & Generated Sumbols
Let $G = (V , Sigma, P, S )$ be a grammar. Let $x in V union Sigma $ be a symbol.
- x is *useful* if there is a derivation\
#align(center, text(12pt)[ $S arrow^* u x v arrow^* w$ with $u, v in (V union Sigma)^*$ and $w in Sigma^*$])
- x is called *useless* if it is not useful
- x is *generating* if $x arrow^* w$ holds for some $w in Sigma^*$
- x is *generated* if there are $u, v in (V union Sigma)^*$ with $S arrow^* u x v$.
Therefore:
- Useful symbols are both generating and generated
- However, generating and generated symbols may not be useful

== Closure properties

= Context-free languages
== Definitions
*Context-Free Grammars*\
A Formal system used to generate the strings of a language. A quadruple ($V, Sigma, P, S$) where\
- $V$ is a set of *variables* or *nonterminals*
- $Sigma$ is an alphabet of *terminals*, disjoint from $V$
- $P$ is a finite set of *production rules*, taken from set $V times (V union Sigma)^*$. We write $A arrow$ instead of $(A, w)$.
- $S in V$ is the *start symbol*.
== PDM
== CFG to PDM
== Closure properties and proofs
== making a grammar productive


/* Maybe irrelevant?
= Context-sensitive
== Linearly-bounded Machines
*/

= Decidable and semi-decidable languages
== Definitions
== TMs
- Computing a function vs recognizing a language
- Acceptance criteria
- Multi-track, multi-tape, nondeterministic
== Proving decidability, semi-decidability or undecidability


= Support lecture

== Pumping lemma

Prove tht L is not regular by the pumping lemma


There exists a $k >= 0$ such that
for every $z in L "for which" |z| >= k$, there exists a splitting
$z = u v w$ with $|u v| <= k$ and $v != epsilon$ such that
for every $i >= 0$ we have $u v^i w in L$

$forall exists forall exists$


$ L = {w w | w in {a, b}^*} $

Take $z = a^k b a^k b$ By the PL, there is a splitting $z = u v w$ such that $|u v| <= k$
and $v != epsilon$

Because the first $k$ symbols are all 'a'

$
 u = a^i, v = a^j, i + j <= k \
 w = a^(k - i - j) b a^k b
$

$z = u v^0 w$ is not in $L$ (prove), so $L$ is nonregular


